name: Test Token Push

on:
  workflow_dispatch:

jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # <- ESSENCIAL! Não deixar ele usar o GITHUB_TOKEN

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create dummy commit
        run: |
          echo "Test at $(date)" >> push-test.txt
          git add push-test.txt
          git commit -m "Testing manual push with classic token"

      - name: Override remote with classic token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PUSH_TOKEN }}@github.com/${{ github.repository }}
          git push origin main
